# Generated by Django 5.0.6 on 2024-06-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('age', models.IntegerField(max_length=50)),
                ('phone', models.IntegerField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=50)),
            ],
        ),
    ]
