# Generated by Django 5.0.6 on 2024-06-25 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_course_student_courses_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Program',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='webapp.program'),
        ),
    ]
