# Generated by Django 5.0.6 on 2024-06-29 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_student_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='courses_taught',
        ),
        migrations.AddField(
            model_name='teacher',
            name='courses_taught',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers_taught', to='webapp.program'),
        ),
    ]
